# Created by Stephen Szwiec on 2022-11-29
# for the Rasulev Computational Chemistry Research Group at North Dakota State University
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
# Please see <http://www.gnu.org/licenses/> for a copy of the GNU General
# Public License.
#
# This script takes a spreadsheet containing xyz coordinates and uses this to create a
# docking arrangements with the specified coorinates as the center of the docking box.
#
# The spreadsheet is generated by the script "spreadsheet.sh" and uses Patchdock output
# as input. If you need to generate a spreadsheet from a Patchdock output file, use the
# script "spreadsheet.sh" to do so.
#
# Spreadsheet format:
# 1st column: receptor name
# 2nd column: ligand name
# 3rd column: x coord
# 4th column: y coordinate
# 5th column: z coordinate
#
#!/bin/bash
prot=$1

for line in $(cat spreadsheet.csv | grep ^$1)
do
	lig=$(echo $line | cut -d',' -f2 -)
	x=$(echo $line | cut -d',' -f4 -)
	y=$(echo $line | cut -d',' -f5 -)
	z=$(echo $line | cut -d',' -f6 -)
	size=50
	cpu=8

	./vina --receptor ./dia/$prot.pdbqt --ligand ./lig/$lig.pdbqt \
		--log ./log/$prot-$lig.log --center_x $x --center_y $y \
		--center_z $z --size_x $size --size_y $size --size_z \
		$size --cpu $cpu

done
